
[general]
import = [
    "./catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 80, lines = 25 }
padding = { x = 8, y = 8 }
decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

# [keyboard]
# option_as_alt = "Both"

# [general]


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
