[window]
dimensions = { columns = 80, lines = 25 }
padding = { x = 8, y = 8 }
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
